import 'package:flutter/foundation.dart';

class EventList with ChangeNotifier{
  final String id;
  final String country;
  final String eventName;
  final String imageUrl1;
  final String imageUrl2;
  final String imageUrl3;
  final String imageUrl4;
  final String location;
  final String description;
  final String day;
  EventList({
    @required this.id,
    @required this.country,
    @required this.eventName,
    @required this.imageUrl1,
    @required this.imageUrl2,
    @required this.imageUrl3,
    @required this.imageUrl4,
    @required this.location,
    @required this.description,
    @required this.day,
  });

}

class EventsLists with ChangeNotifier{
  List<EventList> _items=[
    EventList(
        id: "1",
        country: "Turkey",
        eventName: "Izmir World Fair",
        imageUrl1: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpWP0-qBG2KfEgPyglNwXtbOXcGBW5yv8wdQ&usqp=CAU",
        imageUrl2: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/10/IzmirTurkeyFestepb0310.jpg",
        imageUrl3: "https://ief.izfas.com.tr/images/media/ic_sayfa/88_IEF_GENEL_BANNER.jpg",
        imageUrl4: "https://ief.izfas.com.tr/images/media/ic_sayfa/88_IEF_GENEL_BANNER.jpg",
        location: "Turkey",
        description: "Izmir is well known for for being the host to the oldest festival activity in Turkey, during the multi-theme Izmir World Fair held during early September. The fair is organized by İZFAŞ, which is a depending corporation of Izmir Metropolitan Municipality. The social & musical events that take place simultaneously as the commercial fair had started away as an auxiliary activity to attract popular interest for the fair, but over time the festival became a school by itself. This is one of the most popular Turkey festival.",
        day: "16 September",
    ),
    EventList(
      id: "2",
      country: "Turkey",
      eventName: "Folk Dance Festivals",
      imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/10/FolkDanceFestivalTurkishFestepb0310.jpg",
      imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTe1psMXfIPlYHKRnC1wDF_V-Wib9jCHLiCCQ&usqp=CAU",
      imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQoztb5QXF3P7b5rsWV_B_xch1IEWN9kZTelg&usqp=CAU",
      imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQyyyrxuet9Ax2V6BOTfn9ms5VDizLLYAj7HQ&usqp=CAU",
      location: "Turkey",
      description: "Cultural festivals are most fascinating in cities & resorts that contain the resources to attract internationally renowned acts. Nearly every town has some yearly bash, though several are of limited interest to outsiders. Folk-dance festivals offer an opportunity to see Turkey’s best dance troupes execute various repertoires of Turkish dances in traditional costumes. Well, what else do you want more when you travel to such places! This is amongst the popular Turkey festivals.",
      day: " 27 – 31 October",
    ),
    EventList(
        id: "3",
        country: "Turkey",
        eventName: "Seker & Kurban Festivals" ,
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/10/Sekar-Kurban-TurkishFestepb0310.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRMnOpgEtuzWoASO7oTV8YadX0Z8zP-G-Nudw&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR3pg-ug3NqbgYPI1j4gBg7EoSk8XJKrXgcAQ&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSzHJhZxcKtW6okXVnR3D8gWv586SBnYqjK3A&usqp=CAU",
        location: "Turkey",
        description: "The 3rd day Şeker Bayramı (Sugar Holiday) directly follows Ramadan, celebrated by family reunions and the providing presents and candies to children, and abstaining from going to the restaurants. On the ever of Arife, the night after Kadir Gecesi, you will have to early reservations for tables at good restaurants. The 4thday Kurban Bayramı (Festival of the Sacrifice), in which the sacrificial offering of a sheep represents Abraham’s boy Ishmael (a Koranic version of the Testament story), is marked by the great slaughter of lamb and goats.Throughout the Seker & Kurban festivals travelling becomes difficult so it is recommended to do your bookings well in advance for a seat on any long-distance train or plane. This is one of the most popular festivals in Turkey. Another important thing to keep in mind is that various shops, banking institutions, museums & government office buildings close during these times.",
        day: " 24-25-26 May"),
    EventList(
        id: "4",
        country: "USA",
        eventName: "New Orleans Mardi Gras",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/11/New-Orleans-Mardi-Gras.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRfj0yyeLFcMIwRZrea4ZWN8vZvTyJVq2Vheg&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTbnmx0oj99spITuaPm0QpDYazwb0mc_WFPnQ&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxC9fAL_ejKGmMdtV1rUE_EBoHIAJJY-746A&usqp=CAU",
        location: "New Orleans,USA",
        description: "Of all the festivals celebrated in America, there’s nothing more colourful and thrilling than a Mardi Gras festival, which is marked by a lot of parades and events, all over the city. The New Orleans Mardi Gras is an event that is organised by the social clubs in the city, and people dress up in colourful costumes and parade around the city, and giant floats are driven all over the city as well. Festival-goers throw colourful party cups and other light objects in the air to celebrate the festival, and the dress code for this festival consists of the colours gold, purple and green which signify power, justice and faith. This is considered to be one of the best festivals in the US.",
        day: "25 February"),
    EventList(id: "5",
        country: "USA",
        eventName: "Albuquerque International Balloon Fiesta",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/11/Alburquerque-International-Balloon-Festival.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTnSh-aa0JplmDKQM53KQ1ww48ICTQ9FCO7Yg&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTVIWfllmOrqquKbKCc_vVnRQ5tSsUTSHgbMA&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTkT2GjMhlqIAhsmBnXDj1mIpiebaxIPKBL3Q&usqp=CAU",
        location: "Albuquerque, New Mexico",
        description: "This event, we guarantee, is like nothing you’ve ever seen before in your entire life! Imagine a sky filled with hundreds of different coloured hot air balloons floating in the air. You can turn this imagination into a reality when you visit the Albuquerque International Balloon Fiesta, held every year in Ne Mexico, and witness over 500 air balloons fly over your head, creating an almost magical kind of atmosphere for the visitors. Not only watching, but you will also have an opportunity to fly up on a hot air balloon as well here, making it one of the best festivals in the US.",
        day: "Saturday, 3 October"),
    EventList(id: "6",
        country: "USA",
        eventName: "Coachella Valley Music And Arts Festival",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/11/Coachela-Valley-Music-Festival.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQfxITj8zG9izZxqEcU46R7w9wgEdbB_5vYA&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSF6yYbEuQqo43KNFdsbO_n_WuzoFxf4l9viA&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTs2oFkqRP0PpCBYke8VjK6fg8vTlbT9IrX0g&usqp=CAU",
        location: "Indio, California",
        description: "One could not make a list of the most famous festivals in the country and not mention the Coachella festival, which is a huge annual music festival, which brings in people from all over the world, and large number of the world’s top artists, across different genres come together for a week long celebration of music. It is not unusual to find Hollywood celebrities walking around the festival, just like regular people, as they, just like normal people, come here to enjoy the great music and the delicious food stalls! So put on your best beach clothes and get ready for an insane amount of fun at this music festival in America.",
        day: "10 April – 20 April"),
    EventList(id: "7",
        country: "Switzerland",
        eventName: "Fête Nationale Suisse",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/09/shutterstock_345456020.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSNh4K7NRJgHpweFqKbQF5mkFFFWqs2PGfCpA&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQIilVm1I3yCexDNxJPkvk5gMWAXKawcO6RA&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT17eLBNxy-AwME8-MDM1EATqZiL457rl6Qrg&usqp=CAU",
        location: "Rhino fall, Switzerland",
        description: "Undoubtedly the most eminent festival of any country is its national day and if you are curious about witnessing how the people of Switzerland celebrate their national day then you will get a glimpse of it right now. Imagine thousands of bright decorations, garden barbeques and fireworks near the Rhino falls, isn’t it a splendid view? Do attend the grand national day festivities of Switzerland to absorb every bit of Switzerland culture.",
        day: "1 August"),
    EventList(id: "8",
        country: "Switzerland",
        eventName: "Montreux Jazz Festival",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/09/d310b477c7b881c82fdb05e71f644aef12c32471_2000.jpeg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpxb8uL_OANWQYKvqmTsd2l5o3EByImPbsvw&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSIXfkv6F48-iaIpX70kl-JfvWP8B50e7vH2A&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS9PvS4LZDGkSDedkraK6C80iFQ1quFrqivHg&usqp=CAU",
        location: "Montreux, Switzerland",
        description: "Jazz, an intensified feeling of nonchalance was originated in New Orleans and today its popular worldwide. If you are mesmerized by Jazz, then you must attend the biggest Jazz festival in Switzerland. Montreux Jazz festival is a grand festival celebrated every year in Montreux in the month of July. Many renowned Jazz artist as well as upcoming artists perform in this festival. A must to attend, Montreux Jazz Festival will always be the unforgettable highlight of your life. Whether you have love for jazz or not, this energetic festival will surely make you dance on the tune with its amazing vibe!",
        day: "3 July – 18 July"),
    EventList(id: "9",
        country: "Switzerland",
        eventName: "Geneva Motor Show",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/09/26.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSxrP7SgHpTCUPJ3ngl90S0eSN1hy4BID419A&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT2468zEBZxqiWhLGbOUA2GHjbX-_1ClZzM8Q&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSbVgYXj1jMql_6Kav2kTrmP9xODd2yr9QsUQ&usqp=CAU",
        location: " Geneva, Switzerland",
        description: "Known as the ‘world’s best cat walk for cars’, Geneva Motor Show is held in mid-March every year and is literally a ramp walk for new cars. Many well-known companies display their cars on this show for the first time before the whole world .If you are thinking about witnessing festivals in Geneva, Switzerland then you should definitely buy tickets for Geneva Motor Show. Whether interested in motors or not, this unique festival is worth exploring while holidaying in Switzerland.",
        day:"5March-15 March "),
    EventList(id: "10",
        country: "England",
        eventName: "Hogmanay: New Year In Scotland",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/10/Hogmanay.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQkXleumb1H6VMua5fIdCfRU8dRHs9kBYEj7g&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT9_CTUybWOlPrmVCkeZcTjnp8K7R67SoqnEg&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTIQ4jgDStp9eTCKJLllsmh3JQ0c2Ec0SO1mQ&usqp=CAU",
        location:"Scotland" ,
        description: "In Scotland, the celebration on the last day of the year is popular as Hogmanay. Undoubtedly, this is one of the most famous festivals in United Kingdom, where along with music concerts, games and carnivals, Hogmanay is rejoiced following a local tradition called ‘first footing’. This celebration starts after midnight, where the person enters his neighbour or friend’s house to gift him cake, shortbread, whiskey and cookies, wishing him good luck for the new year. Hogmanay celebration also involves fireball swinging and marching up to the top of Lomond Hills.",
        day: "31 December "),
    EventList(id: "11",
        country: "England",
        eventName: "Robin Hood Festival: An Amazing Celebration",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/10/Robin-Hood-Festival.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTudfTgkPedOFDn-b0M73NTaNhVaoXhBdbBiQ&usqp=CAU",
        imageUrl3: "http://www.robinhoodfestival.org/uploads/2/3/2/5/23259652/editor/maidmarianandrobinhoodphotos.jpg?1560478533",
        imageUrl4: "https://www.visit-nottinghamshire.co.uk/imageresizer/?image=%2fdmsimgs%2f009_Cavalry_of_Heroes_Medieval_Jousting_Knights_on_Horseback_1399651.JPG&action=ProductDetailProFullWidth",
        location: "Sherwood Forest",
        description: "As astounding as the name, this is a delightful week-long celebration and one of the most fun-filled United Kingdom festivals 2020. From pony and horse rides, archery, nature walks to dance and music shows and magic shows; Robin Hood Festival has something for every age group.",
        day: " 4-11 August"),
    EventList(id: "12",
        country: "England",
        eventName: "Guy Fawkes Day",
        imageUrl1: "https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/04/Guy-Fawkes-Day-in-UK-300x156.jpg",
        imageUrl2: "https://www.gettyimages.com/detail/photo/lewes-bonfire-night-royalty-free-image/860818048",
        imageUrl3: "https://www.gettyimages.com/detail/photo/london-fireworks-royalty-free-image/184950189",
        imageUrl4: "https://www.gettyimages.com/detail/photo/lewes-bonfir-east-sussex-united-kingdom-royalty-free-image/597644527",
        location: "All across UK",
        description: "Also called the “Bonfire Night”, this festival is celebrated all over the UK on 5th November. Everywhere in the country, the British light bonfires as well as fireworks, mostly in their back gardens or streets. These days, they have also started lighting these at organized events in public parks. This festival is celebrated to commemorate the situation where Catholic Guy Fawkes’ had failed to blow up the Protestant Houses of Parliament on the 5th of November in 1605.If you’re wondering what makes this one of the most happening festivals in the United Kingdom, you must get East Sussex town of Lewes on this day in the evening. Here you’ll see seven bonfire societies parade going through the town in vibrant costumes, and they’ll be carrying effigies including the Pope’s and Guy Fawkes’ along with and huge flaming crosses. It’s a sight that you wouldn’t want to miss! You’ll be able to see them roll down huge barrels of flaming tar down the streets while they march to the very edge of the town to light up these bonfires. Along with the bonfires here, you’ll also see them burning the effigies they were carrying and setting off spectacular fireworks.",
        day: "5 November"),
    EventList(id: "13",
        country: "Pakistan",
        eventName: "Chilam Joshi Festival ",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSVBY2qUmUpVkh92mm-3U_jeQAUgiA1HHBj1g&usqp=CAU",
        imageUrl1: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSvS-5PoRUbBuk3s_YXL97IiCHgkJOWThFBqA&usqp=CAU",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQU_3I32V5SXbHY0ja7itfn4h2u8wwqZzcn6Q&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTyFu3B-Cpn7192_8Eyb8JmRSP3hyIZRcq47w&usqp=CAU",
        location:"Kalash Valley" ,
        description: "The four-day festival is held in the middle of May. During the festival, men and women meet with the aim of finding a spouse. This festival gives an excellent opportunity to celebrate the beginning of summer and to give a message of peace to the world. During this festival, the people of Kalash pray for the safety of their fields and animals. The people of Kalash adore the music and dance to the beat of drums. Both men and woman share these moments of dancing together during the festivities. The Kalash are for their music and dance festivals.The Ministry of Religious Affairs and Interfaith Harmony, Government of Pakistan has been mandated to celebrate important religious festivals of Minority Communities in Pakistan in a year. The said function Chilam Jusht has been celebrated since 2017 at village Bamburate, Chitral at official level. This Year 2020, is also arranging to celebrate Chilam Jusht during May 2020.",
        day: "13 May – 16 May"),
    EventList(id: "14",
        country: "Pakistan",
        eventName: "Uchal Festival  ",
        imageUrl1: "https://i.ytimg.com/vi/LKjMPD47vLw/maxresdefault.jpg",
        imageUrl2: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTEKlhatLukvbtPOXHqlvuCAmogJrsw-AS7KA&usqp=CAU",
        imageUrl3: "https://i.ytimg.com/vi/fD2WQ_j8ifU/maxresdefault.jpg",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT1axLtxIe6uyUJPhREskV3WL8-QST8r3GHIA&usqp=CAU",
        location:"Kalash Valley" ,
        description: "People of Kalash celebrate the arrival of summer in their own way. Summer festival is very popular among the Kalasha people. In recent years, this festival has also gained popularity all round the world. People from different part of Pakistan and international tourist attend the summer festival in large numbers. During the festival, Kalasha People pay homage to their God by celebrating the harvest and also thanking their God for blessing them with good food and crops. Kalash people take a procession to a high plateau outside the village in Balangkuru and pray to their God, after the prayers the night long dance and party begins which last until the early hours in the morning. Summer festival is celebrated in all the valleys for several days.",
        day: "20 Aug – 22 Aug"),
    EventList(id: "15",
        country: "Pakistan",
        eventName: "Choimus Festival",
        imageUrl1: "https://www.sastaticketpkblog.com/wp-content/uploads/2016/09/Kalash_women_traditional_clothing-min.jpg",
        imageUrl2: "https://www.apricottours.pk/wp-content/uploads/2018/03/kalash-festivals-2.jpg",
        imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRpYIAXcmq3eTM03k0l74i908xxUKL7UoUY9w&usqp=CAU",
        imageUrl4: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQj_nCDS5MidQzilVSU9xMtWDhV7THOT4pz1A&usqp=CAU",
        location:"Kalash Valley" ,
        description: "Kalash Winter festival is also called “Choimus” in the local language. This annually observed event symbolises and forecasts prosperity of the village and its people in the coming year. During the festival People go out to seek foxes which is considered as a good omens. Torch lit processions arrives from nearby villages at the main traditional dancing place called a “Charsue”. The dancing and festivities are held indoor that go late into the night as the local wine is handed around the bonfire. The locals perform rituals for purification during the festival at the dawn of the new year. The tribal elders gather at hilltops to watch the rising sun of the new year that is followed by goat sacrifices made to the Goddess, “Jastak”, and the blood is sprinkled at the temple Jastarkhan.",
        day: "15 Dec – 22 Dec"),


      ];

  List<EventList> get items{
    return[..._items];
  }
  List<EventList> getCountry(String genre){
    return _items.where((prodItem)=>prodItem.country==genre).toList();
  }
  EventList findById(String id){
    return items.firstWhere((prod)=>prod.id==id);
  }
}